/**
 *
 * @author Muhammad Hamza Khan
 */
public class MainFrameNB extends javax.swing.JFrame 
{
        // Constructor 
        public MainFrameNB()
        {
                initComponents();                
                examQuestions.setVisible( false);
                examQuestionSelected.setVisible( false);
                setDefaultCloseOperation(EXIT_ON_CLOSE);
                //setSize(900,600);
                setVisible( true);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings( "unchecked" )
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

                QuestionYearsButtonGroup = new javax.swing.ButtonGroup();
                layeredPane = new javax.swing.JLayeredPane();
                workBench = new javax.swing.JPanel();
                sideBar = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jButton6 = new javax.swing.JButton();
                run = new javax.swing.JButton();
                workSpace = new myWorkSpacePanel();
                examQuestions = new javax.swing.JPanel();
                questionChooserPanel = new javax.swing.JPanel();
                sbsLabel = new javax.swing.JLabel();
                sbs2014 = new javax.swing.JRadioButton();
                sbs2013 = new javax.swing.JRadioButton();
                sbs2012 = new javax.swing.JRadioButton();
                sbs2011 = new javax.swing.JRadioButton();
                ygsLabel = new javax.swing.JLabel();
                ygs2014 = new javax.swing.JRadioButton();
                ysg2013 = new javax.swing.JRadioButton();
                ygs2012 = new javax.swing.JRadioButton();
                ygs2011 = new javax.swing.JRadioButton();
                questionDisplayPanel = new javax.swing.JPanel();
                examQuestionSelected = new javax.swing.JPanel();
                questionDisplayer = new javax.swing.JPanel();
                previousQuestion = new javax.swing.JButton();
                questionLabel = new javax.swing.JLabel();
                nextQuestion = new javax.swing.JButton();
                answerField = new javax.swing.JTextField();
                submitAnswer = new javax.swing.JButton();
                tipsButton = new javax.swing.JButton();
                menuBar = new javax.swing.JMenuBar();
                fileMenu = new javax.swing.JMenu();
                newFileItem = new javax.swing.JMenuItem();
                openFileItem = new javax.swing.JMenuItem();
                saveFileItem = new javax.swing.JMenuItem();
                profileMenu = new javax.swing.JMenu();
                newUserProfileItem = new javax.swing.JMenuItem();
                oldUserProfileItem = new javax.swing.JMenuItem();
                helpMenu = new javax.swing.JMenu();
                creditsMenu = new javax.swing.JMenu();
                modeMenu = new javax.swing.JMenu();
                workBenchModeItem = new javax.swing.JMenuItem();
                examQuestionsModeItem = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(51, 204, 255));
                setForeground(new java.awt.Color(255, 255, 255));

                layeredPane.setBackground(new java.awt.Color(102, 204, 255));
                layeredPane.setName("layeredPane"); // NOI18N
                layeredPane.setOpaque(true);

                workBench.setBackground(new java.awt.Color(51, 204, 255));
                workBench.setName("workBench"); // NOI18N

                sideBar.setBackground(new java.awt.Color(51, 204, 255));
                sideBar.setName("sideBar"); // NOI18N

                jButton1.setText("Battery");
                jButton1.setName("jButton1"); // NOI18N

                jButton2.setText("Bulb");
                jButton2.setName("jButton2"); // NOI18N

                jButton3.setText("Resistor");
                jButton3.setName("jButton3"); // NOI18N

                jButton4.setText("Junction");
                jButton4.setName("jButton4"); // NOI18N

                jButton5.setText("Ammeter");
                jButton5.setName("jButton5"); // NOI18N

                jButton6.setText("Voltmeter");
                jButton6.setName("jButton6"); // NOI18N

                run.setText("RUN");
                run.setName("run"); // NOI18N

                javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
                sideBar.setLayout(sideBarLayout);
                sideBarLayout.setHorizontalGroup(
                        sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sideBarLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                                                .addComponent(run)
                                                .addGap(15, 15, 15)))
                                .addContainerGap())
                );

                sideBarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6});

                sideBarLayout.setVerticalGroup(
                        sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sideBarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(run)
                                .addContainerGap())
                );

                workSpace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                workSpace.setName("workSpace"); // NOI18N
                workSpace.setPreferredSize(new java.awt.Dimension(550, 550));

                javax.swing.GroupLayout workSpaceLayout = new javax.swing.GroupLayout(workSpace);
                workSpace.setLayout(workSpaceLayout);
                workSpaceLayout.setHorizontalGroup(
                        workSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 397, Short.MAX_VALUE)
                );
                workSpaceLayout.setVerticalGroup(
                        workSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout workBenchLayout = new javax.swing.GroupLayout(workBench);
                workBench.setLayout(workBenchLayout);
                workBenchLayout.setHorizontalGroup(
                        workBenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workBenchLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(workSpace, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                workBenchLayout.setVerticalGroup(
                        workBenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(workBenchLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(workBenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(workSpace, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                                        .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                examQuestions.setBackground(new java.awt.Color(51, 204, 255));
                examQuestions.setName("examQuestions"); // NOI18N

                questionChooserPanel.setBackground(new java.awt.Color(51, 204, 255));
                questionChooserPanel.setName("questionChooserPanel"); // NOI18N

                sbsLabel.setText("SBS");
                sbsLabel.setName("sbsLabel"); // NOI18N

                sbs2014.setBackground(new java.awt.Color(51, 204, 255));
                QuestionYearsButtonGroup.add(sbs2014);
                sbs2014.setText("2014");
                sbs2014.setName("sbs2014"); // NOI18N
                sbs2014.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sbs2014ActionPerformed(evt);
                        }
                });

                sbs2013.setBackground(new java.awt.Color(51, 204, 255));
                QuestionYearsButtonGroup.add(sbs2013);
                sbs2013.setText("2013");
                sbs2013.setName("sbs2013"); // NOI18N

                sbs2012.setBackground(new java.awt.Color(51, 204, 255));
                QuestionYearsButtonGroup.add(sbs2012);
                sbs2012.setText("2012");
                sbs2012.setName("sbs2012"); // NOI18N

                sbs2011.setBackground(new java.awt.Color(51, 204, 255));
                QuestionYearsButtonGroup.add(sbs2011);
                sbs2011.setText("2011");
                sbs2011.setName("sbs2011"); // NOI18N

                ygsLabel.setText("YGS");
                ygsLabel.setName("ygsLabel"); // NOI18N

                ygs2014.setBackground(new java.awt.Color(51, 204, 255));
                QuestionYearsButtonGroup.add(ygs2014);
                ygs2014.setText("2014");
                ygs2014.setName("ygs2014"); // NOI18N

                ysg2013.setBackground(new java.awt.Color(51, 204, 255));
                QuestionYearsButtonGroup.add(ysg2013);
                ysg2013.setText("2013");
                ysg2013.setName("ysg2013"); // NOI18N

                ygs2012.setBackground(new java.awt.Color(51, 204, 255));
                QuestionYearsButtonGroup.add(ygs2012);
                ygs2012.setText("2012");
                ygs2012.setName("ygs2012"); // NOI18N

                ygs2011.setBackground(new java.awt.Color(51, 204, 255));
                QuestionYearsButtonGroup.add(ygs2011);
                ygs2011.setText("2011");
                ygs2011.setName("ygs2011"); // NOI18N

                javax.swing.GroupLayout questionChooserPanelLayout = new javax.swing.GroupLayout(questionChooserPanel);
                questionChooserPanel.setLayout(questionChooserPanelLayout);
                questionChooserPanelLayout.setHorizontalGroup(
                        questionChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(questionChooserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(questionChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sbsLabel)
                                        .addComponent(ygsLabel)
                                        .addGroup(questionChooserPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(questionChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ygs2014)
                                                        .addComponent(sbs2013)
                                                        .addComponent(sbs2014)
                                                        .addComponent(sbs2012)
                                                        .addComponent(sbs2011)
                                                        .addComponent(ysg2013)
                                                        .addComponent(ygs2012)
                                                        .addComponent(ygs2011))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                questionChooserPanelLayout.setVerticalGroup(
                        questionChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(questionChooserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sbsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sbs2014)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sbs2013)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sbs2012)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sbs2011)
                                .addGap(18, 18, 18)
                                .addComponent(ygsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ygs2014)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ysg2013)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ygs2012)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ygs2011)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                questionDisplayPanel.setBackground(new java.awt.Color(51, 204, 255));
                questionDisplayPanel.setName("questionDisplayPanel"); // NOI18N
                questionDisplayPanel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                questionDisplayPanelMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout questionDisplayPanelLayout = new javax.swing.GroupLayout(questionDisplayPanel);
                questionDisplayPanel.setLayout(questionDisplayPanelLayout);
                questionDisplayPanelLayout.setHorizontalGroup(
                        questionDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 322, Short.MAX_VALUE)
                );
                questionDisplayPanelLayout.setVerticalGroup(
                        questionDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 543, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout examQuestionsLayout = new javax.swing.GroupLayout(examQuestions);
                examQuestions.setLayout(examQuestionsLayout);
                examQuestionsLayout.setHorizontalGroup(
                        examQuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(examQuestionsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(questionChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(questionDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                examQuestionsLayout.setVerticalGroup(
                        examQuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(examQuestionsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(examQuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(questionDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(questionChooserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                examQuestionSelected.setBackground(new java.awt.Color(51, 204, 255));
                examQuestionSelected.setName("examQuestionSelected"); // NOI18N

                questionDisplayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                questionDisplayer.setName("questionDisplayer"); // NOI18N

                javax.swing.GroupLayout questionDisplayerLayout = new javax.swing.GroupLayout(questionDisplayer);
                questionDisplayer.setLayout(questionDisplayerLayout);
                questionDisplayerLayout.setHorizontalGroup(
                        questionDisplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                questionDisplayerLayout.setVerticalGroup(
                        questionDisplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 242, Short.MAX_VALUE)
                );

                previousQuestion.setText("Previous Question");
                previousQuestion.setName("previousQuestion"); // NOI18N

                questionLabel.setText("SBS 2013 Question 1");
                questionLabel.setName("questionLabel"); // NOI18N

                nextQuestion.setText("Next Question");
                nextQuestion.setName("nextQuestion"); // NOI18N

                answerField.setText("Your Answer");
                answerField.setName("answerField"); // NOI18N
                answerField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                answerFieldActionPerformed(evt);
                        }
                });

                submitAnswer.setText("Submit");
                submitAnswer.setName("submitAnswer"); // NOI18N

                tipsButton.setText("Tips");
                tipsButton.setName("tipsButton"); // NOI18N

                javax.swing.GroupLayout examQuestionSelectedLayout = new javax.swing.GroupLayout(examQuestionSelected);
                examQuestionSelected.setLayout(examQuestionSelectedLayout);
                examQuestionSelectedLayout.setHorizontalGroup(
                        examQuestionSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(examQuestionSelectedLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(examQuestionSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(examQuestionSelectedLayout.createSequentialGroup()
                                                .addComponent(previousQuestion)
                                                .addGap(80, 80, 80)
                                                .addComponent(questionLabel)
                                                .addGap(0, 68, Short.MAX_VALUE))
                                        .addComponent(questionDisplayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(examQuestionSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nextQuestion)
                                        .addGroup(examQuestionSelectedLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(examQuestionSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(submitAnswer)
                                                        .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tipsButton))))
                                .addContainerGap())
                );

                examQuestionSelectedLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nextQuestion, previousQuestion});

                examQuestionSelectedLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {submitAnswer, tipsButton});

                examQuestionSelectedLayout.setVerticalGroup(
                        examQuestionSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, examQuestionSelectedLayout.createSequentialGroup()
                                .addContainerGap(29, Short.MAX_VALUE)
                                .addGroup(examQuestionSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(previousQuestion)
                                        .addComponent(questionLabel)
                                        .addComponent(nextQuestion))
                                .addGroup(examQuestionSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(examQuestionSelectedLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(questionDisplayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(examQuestionSelectedLayout.createSequentialGroup()
                                                .addGap(123, 123, 123)
                                                .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(submitAnswer)
                                                .addGap(18, 18, 18)
                                                .addComponent(tipsButton)))
                                .addContainerGap())
                );

                javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(layeredPane);
                layeredPane.setLayout(layeredPaneLayout);
                layeredPaneLayout.setHorizontalGroup(
                        layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(examQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layeredPaneLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(workBench, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(examQuestionSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                layeredPaneLayout.setVerticalGroup(
                        layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layeredPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(examQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(workBench, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layeredPaneLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(examQuestionSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                layeredPane.setLayer(workBench, javax.swing.JLayeredPane.DEFAULT_LAYER);
                layeredPane.setLayer(examQuestions, javax.swing.JLayeredPane.DEFAULT_LAYER);
                layeredPane.setLayer(examQuestionSelected, javax.swing.JLayeredPane.DEFAULT_LAYER);

                menuBar.setName("menuBar"); // NOI18N

                fileMenu.setText("File");
                fileMenu.setName("fileMenu"); // NOI18N

                newFileItem.setText("New");
                newFileItem.setName("newFileItem"); // NOI18N
                fileMenu.add(newFileItem);

                openFileItem.setText("Open");
                openFileItem.setName("openFileItem"); // NOI18N
                fileMenu.add(openFileItem);

                saveFileItem.setText("Save");
                saveFileItem.setName("saveFileItem"); // NOI18N
                fileMenu.add(saveFileItem);

                menuBar.add(fileMenu);

                profileMenu.setText("Profile");
                profileMenu.setName("profileMenu"); // NOI18N

                newUserProfileItem.setText("New User");
                newUserProfileItem.setName("newUserProfileItem"); // NOI18N
                profileMenu.add(newUserProfileItem);

                oldUserProfileItem.setText("Old User");
                oldUserProfileItem.setName("oldUserProfileItem"); // NOI18N
                profileMenu.add(oldUserProfileItem);

                menuBar.add(profileMenu);

                helpMenu.setText("Help");
                helpMenu.setName("helpMenu"); // NOI18N
                menuBar.add(helpMenu);

                creditsMenu.setText("Credits");
                creditsMenu.setName("creditsMenu"); // NOI18N
                menuBar.add(creditsMenu);

                modeMenu.setText("Mode");
                modeMenu.setName("modeMenu"); // NOI18N

                workBenchModeItem.setText("Work Bench");
                workBenchModeItem.setName("workBenchModeItem"); // NOI18N
                workBenchModeItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                workBenchModeItemActionPerformed(evt);
                        }
                });
                modeMenu.add(workBenchModeItem);

                examQuestionsModeItem.setText("Practice Exam Questions");
                examQuestionsModeItem.setName("examQuestionsModeItem"); // NOI18N
                examQuestionsModeItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                examQuestionsModeItemActionPerformed(evt);
                        }
                });
                modeMenu.add(examQuestionsModeItem);

                menuBar.add(modeMenu);

                setJMenuBar(menuBar);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(layeredPane)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(layeredPane)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>                        

        private void workBenchModeItemActionPerformed(java.awt.event.ActionEvent evt) {                                                  
                // Switching to Work Bench Mode
                examQuestions.setVisible( false);
                examQuestionSelected.setVisible( false);
                workBench.setVisible( true);
        }                                                 

        private void examQuestionsModeItemActionPerformed(java.awt.event.ActionEvent evt) {                                                      
                // Switching to Practice Exam Questions Mode
                workBench.setVisible( false);
                examQuestionSelected.setVisible( false);
                examQuestions.setVisible(  true);
        }                                                     

        private void sbs2014ActionPerformed(java.awt.event.ActionEvent evt) {                                        
                // TODO add your handling code here:
        }                                       

        private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {                                            
                // TODO add your handling code here:
        }                                           

        private void questionDisplayPanelMouseClicked(java.awt.event.MouseEvent evt) {                                                  
                // TODO add your handling code here:
        }                                                 

        /**
         * @param args the command line arguments
         */
        public static void main( String args[] ) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                                if ( "Nimbus".equals(info.getName()) ) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch ( ClassNotFoundException ex ) {
                        java.util.logging.Logger.getLogger(MainFrameNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch ( InstantiationException ex ) {
                        java.util.logging.Logger.getLogger(MainFrameNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch ( IllegalAccessException ex ) {
                        java.util.logging.Logger.getLogger(MainFrameNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
                        java.util.logging.Logger.getLogger(MainFrameNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
        //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MainFrameNB().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify                     
        private javax.swing.ButtonGroup QuestionYearsButtonGroup;
        private javax.swing.JTextField answerField;
        private javax.swing.JMenu creditsMenu;
        private javax.swing.JPanel examQuestionSelected;
        private javax.swing.JPanel examQuestions;
        private javax.swing.JMenuItem examQuestionsModeItem;
        private javax.swing.JMenu fileMenu;
        private javax.swing.JMenu helpMenu;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JLayeredPane layeredPane;
        private javax.swing.JMenuBar menuBar;
        private javax.swing.JMenu modeMenu;
        private javax.swing.JMenuItem newFileItem;
        private javax.swing.JMenuItem newUserProfileItem;
        private javax.swing.JButton nextQuestion;
        private javax.swing.JMenuItem oldUserProfileItem;
        private javax.swing.JMenuItem openFileItem;
        private javax.swing.JButton previousQuestion;
        private javax.swing.JMenu profileMenu;
        private javax.swing.JPanel questionChooserPanel;
        private javax.swing.JPanel questionDisplayPanel;
        private javax.swing.JPanel questionDisplayer;
        private javax.swing.JLabel questionLabel;
        private javax.swing.JButton run;
        private javax.swing.JMenuItem saveFileItem;
        private javax.swing.JRadioButton sbs2011;
        private javax.swing.JRadioButton sbs2012;
        private javax.swing.JRadioButton sbs2013;
        private javax.swing.JRadioButton sbs2014;
        private javax.swing.JLabel sbsLabel;
        private javax.swing.JPanel sideBar;
        private javax.swing.JButton submitAnswer;
        private javax.swing.JButton tipsButton;
        private javax.swing.JPanel workBench;
        private javax.swing.JMenuItem workBenchModeItem;
        private javax.swing.JPanel workSpace;
        private javax.swing.JRadioButton ygs2011;
        private javax.swing.JRadioButton ygs2012;
        private javax.swing.JRadioButton ygs2014;
        private javax.swing.JLabel ygsLabel;
        private javax.swing.JRadioButton ysg2013;
        // End of variables declaration                   
}
